name: Create Asana Ticket

on:
  pull_request:
    types:
      - opened
    branches: [ master, feature/adding-supprt-for-es6 ]

env:
  PROJECT_ID: 1201971528069878

jobs:
  create_asana:
    name: Dependabot Asana
    runs-on: ubuntu-latest
    # if: github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'dependabot-preview[bot]'
    steps:
      - name: Email Asana Task
        id: create
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          # username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          # password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: |
            [${{ github.event.repository.name }}] ${{ github.event.pull_request.title }}
          # Required recipients' addresses:
          to: x+${{ env.PROJECT_ID }}@mail.asana.com
          # Required sender full name (address can be skipped):
          from: AndAnotherDay Github # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: |
            Pull request for package update created: ${{ github.event.pull_request.html_url }} on ${{ github.repository}}.
          # Optional HTML body read from file:
          # html_body: file://README.html
          # Optional carbon copy recipients:
          # cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          # bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          # reply_to: luke@example.com
          # Optional Message ID this message is replying to:
          # in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          # ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          # convert_markdown: true
          # Optional attachments:
          # attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          # priority: low



# The subject will be the task name
# The body will be the task description
# All email attachments will be attached to the task
# You can cc teammates to add them as task collaborators